### ISSUE TITLE
Possible to persist user authentication details in the app indefinitely?

### ISSUE THREAD

**Issue by davidjpeacock** [ekonstantinidis/trevor#63]
Hey there!

I love this app; thank you for providing this! :-)

One improvement I can suggest (ask for?) is whether it's possible to store auth data for longer / indefinitely?  My GitHub password is huge, and I don't know it without referring to my password manager.  It's inconvenient when Trevor expires it and makes me re-authenticate.

Is this something that could be resolved by storing the password some how?

Cheers,
David

**Comment by ekonstantinidis** [comment]
Hi @davidjpeacock! Thanks for you kind words! Trevor gets the authentication token from Travis and it stores it in `localStorage` as you can see in the [controller](https://github.com/ekonstantinidis/trevor/blob/master/www/js/controllers/accounts.js#L160). So it should be stored in the device and you shouldn't have to log in again. You have to login **once** for each service (public & private repos).

ie. I've logged in to trevor (i'm using an iPhone 5S) a couple of months ago and I'm still logged in.

**Comment by davidjpeacock** [comment]
Hey Emmanouil! :-)

That's really curious; this has happened to be twice now.  I'm on an iPhone 5.  I wonder if there's any debug logs or anything I could look at?

**Comment by ekonstantinidis** [comment]
It' an ionic app (cordova) so you might be able to inspect the app using Safari and a cable. If you can do that check localstorage! I would also suggest to uninstall it and install it again!

**Comment by davidjpeacock** [comment]
I'll see what I can find out.  Thanks so much! :-)

**Comment by davidjpeacock** [comment]
Actually, I'm wondering if it's related to GitHub's implementation of 2FA.
